# Generated by Django 4.0.2 on 2022-02-16 11:44

import creditcards.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('from2', models.CharField(choices=[('Cairo', 'Cairo')], max_length=20, null='True', verbose_name='from ')),
                ('to2', models.CharField(choices=[('Aswan', 'Aswan'), ('Alexandria', 'Alexandria'), ('Hurghada', 'Hurghada')], max_length=20, null='True', verbose_name='to ')),
                ('Price', models.IntegerField(null=True)),
                ('date2', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('time2', models.TimeField(default=datetime.datetime.now, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'available',
                'verbose_name_plural': 'availables',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.CharField(choices=[('Cairo', 'Cairo')], max_length=20, null='True', verbose_name='From')),
                ('to', models.CharField(choices=[('Aswan', 'Aswan'), ('Alexandria', 'Alexandria'), ('Hurghada', 'Hurghada')], max_length=20, null='True', verbose_name='To')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Date')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='Time')),
                ('number', models.IntegerField(null='True', verbose_name='Receipt Number')),
                ('Active', models.BooleanField(default='False', null='true')),
                ('Seats', models.IntegerField(default='0')),
                ('card_number', creditcards.models.CardNumberField(max_length=25, null='True', verbose_name='Card Number')),
                ('expiry_date', creditcards.models.CardExpiryField(null='True', verbose_name='Expiry Datec')),
                ('security_code', creditcards.models.SecurityCodeField(max_length=4, null='True', verbose_name='Security Code')),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
            },
        ),
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
            ],
        ),
    ]
