# Generated by Django 4.0.2 on 2022-02-16 18:02

import creditcards.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_available_to2_alter_ride_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='card_number',
            field=creditcards.models.CardNumberField(blank=True, max_length=19, null=True, verbose_name='Card Number'),
        ),
    ]
